### ISSUE TITLE
obm migration error

### ISSUE THREAD

**Issue by ytjohn** [RackHD/on-http#383]
I pulled a mongo dump from one of our production rackhd servers onto our testing vm and ran the [obm migration script](https://gist.github.com/dalebremner/a04868e8c9ba9820a3d931432999342a).  It appeared to go through each node, collecting obmSettings to obmSavesToBeDone, but partially through it threw an exception.

```
5706fa2625a985c051c7d80e
5706fcd525a985c051c7d83a
5707ca0b0f9ac06f50fa9e62
Saving: 5707ca0b0f9ac06f50fa9e62 {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:fd:55:a4"}}
5707cdb50f9ac06f50fa9e63
Saving: 5707cdb50f9ac06f50fa9e63 {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:fc:5a:3c"}}
5707d56e0f9ac06f50fa9e64
Saving: 5707d56e0f9ac06f50fa9e64 {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:fd:63:c0"}}
5707f54d0f9ac06f50fa9e66
Saving: 5707f54d0f9ac06f50fa9e66 {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:fd:5e:20"}}
570813da58bbc61c05f23107
Saving: 570813da58bbc61c05f23107 {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:fd:59:7c"}}
572294e383b26dd761a50899
Saving: 572294e383b26dd761a50899 {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:f7:36:d4"}}
57229da383b26dd761a5089b
Saving: 57229da383b26dd761a5089b {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:fd:64:a4"}}
57229ef283b26dd761a5089c
Saving: 57229ef283b26dd761a5089c {"service":"ipmi-obm-service","config":{"user":"root","password":"password","host":"00:8c:fa:fd:59:52"}}
buffer.js:138
    throw new TypeError('must start with number, buffer, array or string');
    ^
​
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:138:11)
    at new Buffer (buffer.js:65:10)
    at Encryption.encrypt (/vagrant/scratch/ombmigrator/node_modules/on-core/lib/common/encryption.js:35:13)
    at EncryptionService.encrypt (/vagrant/scratch/ombmigrator/node_modules/on-core/lib/services/encryption.js:25:36)
    at /vagrant/scratch/ombmigrator/node_modules/on-core/lib/models/obms.js:48:35
    at /vagrant/scratch/ombmigrator/node_modules/lodash/index.js:3395:24
    at /vagrant/scratch/ombmigrator/node_modules/lodash/index.js:3073:15
    at baseForOwn (/vagrant/scratch/ombmigrator/node_modules/lodash/index.js:2046:14)
    at Function.mapValues (/vagrant/scratch/ombmigrator/node_modules/lodash/index.js:3394:9)
    at baseWrapperValue (/vagrant/scratch/ombmigrator/node_modules/lodash/index.js:2768:30)
    at LodashWrapper.wrapperValue (/vagrant/scratch/ombmigrator/node_modules/lodash/index.js:6124:14)
    at _encryptSecrets (/vagrant/scratch/ombmigrator/node_modules/on-core/lib/models/obms.js:51:12)
    at ObmsModelFactory.Model.extend.beforeCreate (/vagrant/scratch/ombmigrator/node_modules/on-core/lib/models/obms.js:103:13)
    at fn (/vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:41:10)
    at /vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at iterate (/vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:275:9)
    at Object.async.forEachSeries.async.eachSeries (/vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:211:22)
    at Object.runner.beforeCreate (/vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:44:9)
    at /vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/lib/waterline/query/dql/create.js:180:17
    at /vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:699:13
    at iterate (/vagrant/scratch/ombmigrator/node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:256:13)
```

The last node in question:

```
db.nodes.find({"_id": ObjectId("57229ef283b26dd761a5089c")})
{ "_id" : ObjectId("57229ef283b26dd761a5089c"), "autoDiscover" : false, "createdAt" : ISODate("2016-04-28T23:38:26.900Z"), "identifiers" : [  "00:8c:fa:f2:92:7a" ], "name" : "os-r06-c04-s02", "obmSettings" : [ 	{ 	"service" : "ipmi-obm-service", 	"config" : { 	"user" : "root", 	"password" : "password", 	"host" : "00:8c:fa:fd:59:52" } } ], "relations" : [ 	{ 	"relationType" : "enclosedBy", 	"targets" : [ 	"5706ae5225a985c051c7d624" ] } ], "sku" : ObjectId("57041c42f37ec2a960d3ef09"), "type" : "compute", "updatedAt" : ISODate("2016-04-29T19:17:14.429Z") }
```

**Comment by ytjohn** [comment]
@dalebremner @brianparry @keedya

**Comment by keedya** [comment]
@ytjohn can you add all  nodes

**Comment by keedya** [comment]
Encryption service needs to be started in on-core in case old obmsettings password is saved un-encrypted

**Comment by keedya** [comment]
Temporary fix available at 
https://gist.github.com/ytjohn/77e13ef159943347520bfc52c89f3cfb

**Comment by amymullins** [comment]
The tool was removed from the gist and a repo was created for it: https://github.com/dalebremner/rackhd-obm-migration
